name: CI Checks
 
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.24

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Test
      run: make test

    - name: Coverage Check
      run: make coverage

    - name: Generate Report
      run: make report

    - name: Copy Files
      run: |
        mkdir reports
        cp cover.html reports/.
 
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: reports

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
 
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
 
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
 
    - name: Build
      run: make build
 
    - name: Copy Files
      run: |
        mkdir  artifacts
        cp ms artifacts/.
 
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: ms
        path: artifacts

  deliver:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: ms
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Still in experimentation phase
        draft: true
        prerelease: true

    - name: Upload Release Binary
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN:
            ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url:
            ${{ steps.create_release.outputs.upload_url }}
        asset_path: ms
        asset_name: ms
        asset_content_type: application/octet-stream
